### ISSUE TITLE
Whenever i click on dont have an account app crash,help me ? here is my logcat

### ISSUE THREAD

**Issue by Nikku007** [willteksoftwares/personal-budgeting-app#1]
2021-07-22 17:04:42.637 306-306/? E/Layer: [Surface(name=Task=68)/@0x4df8653 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.637 306-306/? E/Layer: [Surface(name=Task=68)/@0x4df8653 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.637 306-306/? E/Layer: [Surface(name=Task=1)/@0x7cd19a0 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.637 306-306/? E/Layer: [Surface(name=Task=1)/@0x7cd19a0 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.651 306-306/? E/Layer: [Surface(name=Task=68)/@0x4df8653 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.651 306-306/? E/Layer: [Surface(name=Task=1)/@0x7cd19a0 - animation-leash#0] No local sync point found
2021-07-22 17:04:43.521 369-605/? E/IPCThreadState: binder thread pool (1 threads) starved for 107 ms
2021-07-22 17:04:47.852 9162-9162/com.example.personalbudgetingapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.personalbudgetingapp, PID: 9162
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.personalbudgetingapp/com.example.personalbudgetingapp.Registration_Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at com.example.personalbudgetingapp.Registration_Activity.onCreate(Registration_Activity.java:28)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-07-22 17:04:47.935 519-558/system_process E/libprocessgroup: AddTidToCgroup failed to write '9200'; fd=113: Invalid argument
2021-07-22 17:04:47.935 519-558/system_process E/libprocessgroup: Failed to add task into cgroup
2021-07-22 17:04:49.066 8511-8538/com.google.android.googlequicksearchbox E/MDD: DownloadProgressMonitor: Can't find file group for uri: android://com.google.android.googlequicksearchbox/files/sharedminusonemodule/shared/SharedMinusOneData.pb.tmp
2021-07-22 17:04:49.502 186-616/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2021-07-22 17:04:49.507 186-616/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
2021-07-22 17:04:54.055 417-417/? E/wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
2021-07-22 17:04:54.055 417-417/? E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
2021-07-22 17:04:55.758 415-415/? E/netmgr: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument
2021-07-22 17:04:55.774 415-415/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
2021-07-22 17:05:04.703 186-616/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2021-07-22 17:05:04.705 186-616/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied

**Comment by willteksoftwares** [comment]
Change logcat from verbose to error, to get a more precise error.

**Comment by Nikku007** [comment]
oops sorry here is error 

2021-07-22 17:04:42.637 306-306/? E/Layer: [Surface(name=Task=68)/@0x4df8653 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.637 306-306/? E/Layer: [Surface(name=Task=68)/@0x4df8653 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.637 306-306/? E/Layer: [Surface(name=Task=1)/@0x7cd19a0 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.637 306-306/? E/Layer: [Surface(name=Task=1)/@0x7cd19a0 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.651 306-306/? E/Layer: [Surface(name=Task=68)/@0x4df8653 - animation-leash#0] No local sync point found
2021-07-22 17:04:42.651 306-306/? E/Layer: [Surface(name=Task=1)/@0x7cd19a0 - animation-leash#0] No local sync point found
2021-07-22 17:04:43.521 369-605/? E/IPCThreadState: binder thread pool (1 threads) starved for 107 ms
2021-07-22 17:04:47.852 9162-9162/com.example.personalbudgetingapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.personalbudgetingapp, PID: 9162
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.personalbudgetingapp/com.example.personalbudgetingapp.Registration_Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at com.example.personalbudgetingapp.Registration_Activity.onCreate(Registration_Activity.java:28)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-07-22 17:04:47.935 519-558/system_process E/libprocessgroup: AddTidToCgroup failed to write '9200'; fd=113: Invalid argument
2021-07-22 17:04:47.935 519-558/system_process E/libprocessgroup: Failed to add task into cgroup
2021-07-22 17:04:49.066 8511-8538/com.google.android.googlequicksearchbox E/MDD: DownloadProgressMonitor: Can't find file group for uri: android://com.google.android.googlequicksearchbox/files/sharedminusonemodule/shared/SharedMinusOneData.pb.tmp
2021-07-22 17:04:49.502 186-616/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2021-07-22 17:04:49.507 186-616/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
2021-07-22 17:04:54.055 417-417/? E/wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
2021-07-22 17:04:54.055 417-417/? E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
2021-07-22 17:04:55.758 415-415/? E/netmgr: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument
2021-07-22 17:04:55.774 415-415/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
2021-07-22 17:05:04.703 186-616/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2021-07-22 17:05:04.705 186-616/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied

**Comment by willteksoftwares** [comment]
Ensure that you have innitialized the textview that you tap with it's id.

Like this....

 yourtv=findVIewById(R.id.yourid);

**Comment by Nikku007** [comment]
forgive me but i write code which you provided in tutorial series but wrong 

here is my code
public class LoginActivity extends AppCompatActivity {

    private EditText email,password;
    private Button loginBtn;
    private TextView loginQn;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        email = findViewById(R.id.email);
        password = findViewById(R.id.password);
        loginBtn = findViewById(R.id.loginBtn);
        loginQn = findViewById(R.id.loginQn);

        loginQn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(LoginActivity.this, Registration_Activity.class);
                startActivity(intent);
            }
        });
    }
}

**Comment by willteksoftwares** [comment]
Hey, the error is on the activities, either in the login activity or
registration activity. Ensure the views in the both activities are
innitialized with the correct IDs and linked to the right java files... It
might also be a typo or something. Also after checking all that, you might
want to uninstall the app from your phone, and then run again in android
studio to re install it.

**Comment by Nikku007** [comment]
Ok i will do that now

**Comment by Nikku007** [comment]
Finally i start again from your youtube video course and i create again fresh app now its working fine thank you so much for your assistance and patience...

**Comment by willteksoftwares** [comment]
You are welcome.
